### ISSUE TITLE
Update request: standard image versions

### ISSUE THREAD

**Issue by amandadebler** [deislabs/kind-vscode#14]
The standard images list appears to be a bit outdated. I guess this has mostly to do with the extension being made for kind 0.4.0, not 0.5.1 (current version installed with choco on Windows) or 0.6.0.

**Comment by amandadebler** [comment]
Looking at the code, I think I can manage this one along the same lines it's currently handled. Caveat: I know precious little about TypeScript or the VSCode plugin model 😄

**Comment by itowlson** [comment]
@amandadebler aaugh, sorry for missing this and your other issues.  For some reason I wasn't watching this repo.  I am now, and will get onto your comments!
