### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by amandadebler** [deislabs/kind-vscode#15]
There are a few package dependencies that have high vulnerabilities:

tslint > js-yaml is: ^3.7.0    should be: ^3.13.1
vscode > gulp-untar > tar   is: ^2.2.1     should be: ^2.2.2
vscode > gulp-untar > tar > fstream    is: ^1.0.2    should be: ^1.0.12

**Comment by itowlson** [comment]
Fixed via #20.
